### ISSUE TITLE
Please Release Version: 3.1.6

### ISSUE THREAD

**Issue by sunflower-seed** [webjars/diff2html#13]
Currently it seems to be **not** possible to use bower (and also bowergithub).

Bower leads to the following error at compile time:

`Failed to execute goal on project ***: Could not resolve dependencies for project ***: Failed to collect dependencies at org.webjars.bower:diff2html:jar:3.1.6 -> org.webjars.bower:diff:jar:[4.0.2]: No versions available for org.webjars.bower:diff:jar:[4.0.2] within specified range -> [Help 1]`

Also diff in v.4.0.2 is not createable.

**Comment by jamesward** [comment]
It looks like this package is falling back to the NPM `package.json` definition. There is a dependency in there on diff `4.0.2` but that release doesn't exist as a Bower package:
https://github.com/flitbit/diff/releases

But the NPM WebJar for this should work:
`org.webjars.npm diff2html 3.1.6`

Let me know if not.

**Comment by sunflower-seed** [comment]
Yeah its working :+1:
